title: Your awesome title
email: your-email@domain.com
author: GitHub User
copyright: Unpublished Work (cleft) 2017-{currentYear} {author}
description: Write an awesome description for your new site here. You can edit
baseurl: ""
url: "http://localhost:4000/"
favicon: ""
yat:
  date_format: "%b %d, %Y"
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-admin
jekyll_admin:
  homepage: "pages"